---
name: Auto release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
      - ".gitignore"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: "v"